name: "Chromatic"

on:
  pull_request:
    branches:
      - chromatic

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
            rm -rf node_modules package-lock.json
            npm install --legacy-peer-deps

      - name: Run Storybook build
        run: |
          npm run build-storybook -- --output-dir=/tmp/chromatic

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
