name: Cypress Tests

on:
  push:
    branch:
      - user-flow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Start development server
        run: |
          cd /home/runner/work/design-system-testing/design-system-testing/packages/ui
          npm run dev & npx wait-on http://localhost:6006
      - name: Cypress run
        run: |
          cd /home/runner/work/design-system-testing/design-system-testing/packages/ui
          npx cypress run --config-file packages/ui/cypress.config.js --spec 'packages/ui/cypress/e2e/**/*.cy.{js,jsx,ts,tsx}' --record false