name: Cypress Tests

on:
  push:
    branch:
      - user-flow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: | 
            npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: /home/runner/work/design-system-testing/design-system-testing/packages/ui  # packages/ui 디렉토리로 이동
          with:
            start: npm run dev